### ISSUE TITLE
Missing doc for navbar and frame !

### ISSUE THREAD

**Issue by sebius8780** [maciej-czekala/corona_ui_framework#1]
Hello and a big thank you for your template which is :
1 Working as described
2 Allow me to create great prototypes even if i am a real mess regarding graphical composition.

That being said ( I didn't know where to write it ) I still miss the navbar and frame documentation.

Can we add a menu button on nav bar by example ? ( back seems to use directly the right icon ).
What is the use / purpose of frame ?

Thank you !

**Comment by maciej-czekala** [comment]
Hi,
I have added doc for navbar, please have a look. At the moment navbar is quite limited, more options (like menu button) will be added in the future.

Frame is used mainly for elements on timeline screens and composition of single information components. It is a base for card element from material design.

**Comment by maciej-czekala** [comment]
I have added functionality to add icons to navbar. You have menu buttons as standard and can add more icons manually.
