### ISSUE TITLE
sample app crash after start

### ISSUE THREAD

**Issue by e1itconsult** [maciej-czekala/corona_ui_framework#3]
Hi,
tried your sample app on windows with corona sdk Build: 2017.3135
App crashes on simulator at startup:

10:36:15.484  Copyright (C) 2009-2017  C o r o n a   L a b s   I n c .
10:36:15.484  	Version: 3.0.0
10:36:15.484  	Build: 2017.3135
10:36:15.484  Platform: Sensation / x64 / 6.1 / AMD FirePro V3900 (FireGL V) Graphics Adapter / 4.3.12629 Compatibility Profile Context FireGL 13.251.1.0 / 2017.3135 / de_DE | DE | de_DE | de
10:36:15.484  Loading project from:   C:\Users\atisfrit\OneDrive\_Development\_Corona\02_Samples\corona_ui_framework-master
10:36:15.484  Project sandbox folder: C:\Users\atisfrit\AppData\Local\Corona Labs\Corona Simulator\Sandbox\corona_ui_framework-master-9AAA2253EE083509C0D5B29804416E09\Documents
10:36:16.324  name	Sensation
10:36:16.324  iosDeviceName	iPhone 6
10:36:16.334  WARNING: Could not load font ionicons. Using default font.
10:36:16.334  WARNING: Could not load font ionicons. Using default font.
10:36:16.334  WARNING: Could not load font Roboto-Medium. Using default font.
10:36:16.334  WARNING: Could not load font ionicons. Using default font.
10:36:16.334  WARNING: Could not load font Roboto-Medium. Using default font.
10:36:16.334  WARNING: Could not load font Roboto-Medium. Using default font.
10:36:16.334  warrning: icon is required!
10:36:16.334  WARNING: Could not load font Roboto-Medium. Using default font.
10:36:16.334  warrning: icon is required!
10:36:16.334  WARNING: Could not load font Roboto-Medium. Using default font.
10:36:16.334  warrning: icon is required!
10:36:16.334  WARNING: Could not load font Roboto-Medium. Using default font.
10:36:16.344  WARNING: Could not load font Roboto-Medium. Using default font.
10:36:16.344  WARNING: Could not load font Roboto-Medium. Using default font.
10:36:16.344  WARNING: Could not load font Roboto-Medium. Using default font.
10:36:16.354  WARNING: Could not load font Roboto-Medium. Using default font.
10:36:16.354  ERROR: Runtime error
10:36:16.354  ?:0: attempt to perform arithmetic on field 'height' (a nil value)
10:36:16.354  stack traceback:
10:36:16.354  	?: in function 'ratio'
10:36:16.354  	C:\Users\atisfrit\OneDrive\_Development\_Corona\02_Samples\corona_ui_framework-master\main.lua:277: in main chunk

**Comment by maciej-czekala** [comment]
Just updated example. https://raw.githubusercontent.com/maciej-czekala/corona_ui_framework/master/main.lua

have a try again.

Thanks
