### ISSUE TITLE
Navbar icons not working

### ISSUE THREAD

**Issue by DanS2D** [maciej-czekala/corona_ui_framework#4]
You stated that one should download the icon pack here: https://ionicons.com/ and place them next to main.lua

After doing that, there are still no icons displayed. The icons are also svg, do you support svg?
I noticed that the plugin hasn't been updated in a while, would you consider open sourcing it so I can see how it works?

The lack of documentation and ability to see the code makes issues like this incredibly difficult to diagnose.

Thank you

**Comment by maciej-czekala** [comment]
please download icons from: https://ionicons.com/v2/

corona marketplace does not reflect proper update time for some reason. I do update framework at least once a month.

Please let me know which parts you would be interested in and I will try to prepare better documentation.
