### ISSUE TITLE
newStatusbar : how to set the background color

### ISSUE THREAD

**Issue by marcelloh** [maciej-czekala/corona_ui_framework#7]
I can't find how this is done.
I tried:
```
local statusbar = ui.newStatusbar({
		parent = viewGroup,
		fillColor = {0.18,0.35,0.58}

	})
```

**Comment by maciej-czekala** [comment]
Hi,

what are you trying to do?
after creation lower the status bar to be in correct position.

`statusbar.y = statusbar.height*.5`

if you want to change color use "color" instead of "fillColor"

Let me know how else I can help you.
